name: Build and Push Docker Container

on:
  workflow_dispatch:
    inputs:
      dockerfile-name:
        required: true
        default: Dockerfile
      image-name:
        required: true
        default: label-studio-OG
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ github.event.inputs.dockerfile-name }}
          push: true
          tags: anandsr2522/python_anaconda:${{ github.event.inputs.image-name }}
          #tags: mattburnsoutline/outline-global:${{ github.event.inputs.image-name }}
          #cache-from: none
